apiVersion: apps/v1
kind: Deployment
metadata:
  name: assistx-dummy-apps
  namespace: dummyapps-dev
  labels:
    app: dummyapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummyapps
  template:
    metadata:
      labels:
        app: dummyapps
    spec:
      containers:
      - name: dummyapps
        image: josaphatyoga/fastapi-burncpu:8f1dd74a99933a86ec5e03ea8912efd8424e71ad-dev
        ports:
        - containerPort: 8080