apiVersion: apps/v1
kind: Deployment
metadata:
  name: assistx-dummy-apps
  namespace: dummyapps-dev
  labels:
    app: dummyapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummyapps
  template:
    metadata:
      labels:
        app: dummyapps
    spec:
      containers:
      - name: dummyapps
        image: josaphatyoga/fastapi-burncpu:b47c0f19210b9bf4f85fd08e4f7430aa54297634-dev
        ports:
        - containerPort: 8080