apiVersion: apps/v1
kind: Deployment
metadata:
  name: assistx-dummy-apps
  namespace: dummyapps-dev
  labels:
    app: dummyapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummyapps
  template:
    metadata:
      labels:
        app: dummyapps
    spec:
      containers:
      - name: dummyapps
        image: josaphatyoga/fastapi-burncpu:806dda1b5e05a901fc6f9ebad96c9644bd3fd644-dev
        ports:
        - containerPort: 8080